version: "3.8"

services:
  shopping_cart_api:
    build: .
    image: shopping_cart_api
    container_name: shopping_cart_api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - shopping_cart_database:/var/lib/postgresql/data/

volumes:
  shopping_cart_database: