version: "3.8"

services:
  shopping_cart_api:
    build: .
    image: shopping_cart_api
    container_name: shopping_cart_api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - database
    env_file:
      - .env
  database:
    image: postgres
    restart: always
    volumes:
      - shopping_cart_database:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  shopping_cart_database: