# Generated by Django 4.1.3 on 2022-12-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('authentication', '0003_remove_contactinformation_user_and_more'),
        ('shopping_cart', '0004_shoppingcart_products_alter_orderedproduct_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shopping_cart.shoppingcart', verbose_name='Shopping cart'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='products.product', verbose_name='Product in order'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='shopping_cart.shoppingcart', verbose_name='Cart with products')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='authentication.contactinformation', verbose_name='Customer information')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
